### ISSUE TITLE
TPA is not configured to support precompiled templates across all top level modules

### ISSUE THREAD

**Issue by donataswix** [wix/generator-wix-angular#6]
By default generated TPA would have `*.preload.haml` views compiled as part of `*AppInternal` module which is not shared between other modules.

**Comment by shahata** [comment]
Fixed!

**Comment by shahata** [comment]
(in https://github.com/wix/generator-wix-angular/commit/d1dfa660c856d7409f9c11a6c958669a2fa3536a)
